[package]
name = "bevy_state_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = ["bevy_ui"] }

[dev-dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_text",
    "default_font",
    "bevy_winit",
    "x11",
] }

[[example]]
name = "simple"
